module.exports.myDetails = {
  name: "Venkatesh C",
  email: "venkatbe26494@gmail.com",
  phone: "7402161837",
  runningText: ["a Full Stack Web Developer.", "Skilled in Svelte & TailwindCSS.", "Building seamless user experiences.", "Experienced with Node.js & MongoDB.", "Experienced with GIT & NGINX."],
  socials: [
    {
      type: "LinkedIn",
      url: "https://www.linkedin.com/in/venkatesh-c-4412439a/",
    },
    {
      type: "GitHub",
      url: "https://github.com/venky-123-debug",
    },
  ],
  professionalObjective: "Aiming to excel in IT by embracing new roles, responsibilities, and technologies. Seeking a Full Stack Software Developer role to leverage my skills in crafting efficient, scalable solutions that drive user satisfaction and business growth.",
  professionalSummary: {
    experience: `1.9 years in web development, specializing in HTML, CSS, JavaScript, Svelte, TailwindCSS, MongoDB, Nginx, and Redis.`,
    skills: ["Designing and implementing RESTful APIs using NodeJS", "Managing MongoDB database", "Deploying applications using Nginx", "Managing server-side caching with Redis", "Version control using Git and Bitbucket", "Working on Linux and Windows operating systems", "Quick learner", "Can work independently or in a team environment"],
  },
  technicalSummary: {
    languages: ["JavaScript", "HTML", "Node.js"],
    frontendFrameworks: ["Svelte"],
    cssFrameworks: ["TailwindCSS", "Bootstrap v4"],
    databaseSystems: ["MongoDB"],
    webServers: ["Nginx"],
    caching: ["Redis"],
    versionControl: ["Git", "Bitbucket"],
    operatingSystem: ["Linux", "Windows"],
    cloudPlatforms: ["AWS", "GCP"],
  },
  educationalQualification: [
    {
      course: "M.E (CAD / CAM)",
      percentage: "81.1",
      yearCompleted: "2019",
      institution: "Arignar Anna Institute Of Science and Technology",
      university: "Anna University Chennai",
    },
    {
      course: "BE (MECH)",
      percentage: "76.3",
      yearCompleted: "2015",
      institution: "Rajalakshmi Engineering College",
      university: "Anna University Chennai",
    },
    {
      course: "HSC",
      percentage: "86.25",
      yearCompleted: "2011",
      institution: "St.Joseph’s Hr. Sec. School",
      university: "State Board of Tamil Nadu",
    },
    {
      course: "SSLC",
      percentage: "90.6",
      yearCompleted: "2009",
      institution: "St.Joseph’s Hr. Sec. School",
      university: "State Board of Tamil Nadu",
    },
  ],
  professionalExperience: [
    {
      role: "Junior Software Developer",
      company: "Docchain.io by Print2Block",
      startDate: "November 2022",
      current: true,
    },
    {
      role: "Full Stack Software Developer Intern",
      company: "Docchain.io by Print2Block",
      startDate: "July 2022",
      endDate: "November 2022",
    },
  ],
  projects: [
    {
      title: "Manufacturer Application - Blockchain Secured Labels",
      client: "Internal Project",
      description: "Developed and managed a backend system for a blockchain-secured labeling application.",
      responsibilities: ["Handled backend development using Node.js", "Implemented JWT authentication and SHA-256 hashing", "Managed MongoDB and Redis", "Configured Nginx and PM2 for deployment", "Developed the navigation section using Svelte and TailwindCSS"],
      duration: "May 2024 to Present",
      technologies: ["Node.js", "MongoDB", "Redis", "JWT", "SHA-256", "Nginx", "PM2", "SSL Certificates"],
    },
    {
      title: "KYC Management System",
      client: "Internal Project",
      description: "Developed a system for user identity verification processes similar to banks.",
      responsibilities: ["Backend development with Node.js and JWT", "Data storage and retrieval using MongoDB", "Integrated Redis for caching", "Managed deployment with Nginx and PM2"],
      duration: "January 2024 to April 2024",
      technologies: ["Node.js", "MongoDB", "Redis", "JWT", "SHA-256", "Nginx", "PM2"],
    },
    {
      title: "Company’s Main Application - Document Issuing Platform",
      client: "Internal Project",
      description: "A blockchain-based document issuing platform for managing documents.",
      responsibilities: ["Developed UI using Svelte and TailwindCSS", "Implemented features with JavaScript", "Collaborated with designers and backend teams", "Performed code reviews"],
      duration: "March 2023 to December 2023",
      technologies: ["Svelte", "TailwindCSS", "JavaScript"],
    },
  ],
  personalInfo: {
    dateOfBirth: "26-04-1994",
    nationality: "Indian",
    gender: "Male",
    city: "Chennai",
    state: "Tamil Nadu",
    languages: ["English", "Tamil", "Telugu"],
    address: "Senthil Nagar, 8th Street, Vignesh Villa 2nd Floor, Perungudi, Chennai-96",
  },
  declaration: "I hereby declare that the information furnished above is true and correct to the best of my knowledge and belief. I will solely be responsible for any discrepancy found in them.",
  signature: "Venkatesh C",
}
